export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';

export const FETCH_COURSES_BY_PROFESSOR_REQUEST = 'FETCH_COURSES_BY_PROFESSOR_REQUEST';
export const FETCH_COURSES_BY_PROFESSOR_SUCCESS = 'FETCH_COURSES_BY_PROFESSOR_SUCCESS';
export const FETCH_COURSES_BY_PROFESSOR_FAILURE = 'FETCH_COURSES_BY_PROFESSOR_FAILURE';

export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';

export const FETCH_COURSE_BY_ID_REQUEST = 'FETCH_COURSE_BY_ID_REQUEST';
export const FETCH_COURSE_BY_ID_SUCCESS = 'FETCH_COURSE_BY_ID_SUCCESS';
export const FETCH_COURSE_BY_ID_FAILURE = 'FETCH_COURSE_BY_ID_FAILURE';

export const FETCH_COURSES_BY_STUDENT_REQUEST = 'FETCH_COURSES_BY_STUDENT_REQUEST';
export const FETCH_COURSES_BY_STUDENT_SUCCESS = 'FETCH_COURSES_BY_STUDENT_SUCCESS';
export const FETCH_COURSES_BY_STUDENT_FAILURE = 'FETCH_COURSES_BY_STUDENT_FAILURE';

export const UPDATE_COURSE_REQUEST = 'UPDATE_COURSE_REQUEST';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_FAILURE = 'UPDATE_COURSE_FAILURE';

export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAILURE = 'DELETE_COURSE_FAILURE';
