export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';

export const FETCH_COURSES_BY_PROFESSOR_REQUEST = 'FETCH_COURSES_BY_PROFESSOR_REQUEST';
export const FETCH_COURSES_BY_PROFESSOR_SUCCESS = 'FETCH_COURSES_BY_PROFESSOR_SUCCESS';
export const FETCH_COURSES_BY_PROFESSOR_FAILURE = 'FETCH_COURSES_BY_PROFESSOR_FAILURE';
