export const FETCH_MY_ENROLLMENTS_REQUEST = 'FETCH_MY_ENROLLMENTS_REQUEST';
export const FETCH_MY_ENROLLMENTS_SUCCESS = 'FETCH_MY_ENROLLMENTS_SUCCESS';
export const FETCH_MY_ENROLLMENTS_FAILURE = 'FETCH_MY_ENROLLMENTS_FAILURE';

export const ENROLL_IN_COURSE_REQUEST = 'ENROLL_IN_COURSE_REQUEST';
export const ENROLL_IN_COURSE_SUCCESS = 'ENROLL_IN_COURSE_SUCCESS';
export const ENROLL_IN_COURSE_FAILURE = 'ENROLL_IN_COURSE_FAILURE';

export const CANCEL_ENROLLMENT_REQUEST = 'CANCEL_ENROLLMENT_REQUEST';
export const CANCEL_ENROLLMENT_SUCCESS = 'CANCEL_ENROLLMENT_SUCCESS';
export const CANCEL_ENROLLMENT_FAILURE = 'CANCEL_ENROLLMENT_FAILURE';

export const FETCH_ENROLLMENTS_BY_COURSE_REQUEST = 'FETCH_ENROLLMENTS_BY_COURSE_REQUEST';
export const FETCH_ENROLLMENTS_BY_COURSE_SUCCESS = 'FETCH_ENROLLMENTS_BY_COURSE_SUCCESS';
export const FETCH_ENROLLMENTS_BY_COURSE_FAILURE = 'FETCH_ENROLLMENTS_BY_COURSE_FAILURE';
