export const CREATE_GRADE_REQUEST = 'CREATE_GRADE_REQUEST';
export const CREATE_GRADE_SUCCESS = 'CREATE_GRADE_SUCCESS';
export const CREATE_GRADE_FAILURE = 'CREATE_GRADE_FAILURE';

export const UPDATE_GRADE_REQUEST = 'UPDATE_GRADE_REQUEST';
export const UPDATE_GRADE_SUCCESS = 'UPDATE_GRADE_SUCCESS';
export const UPDATE_GRADE_FAILURE = 'UPDATE_GRADE_FAILURE';

export const FETCH_GRADES_BY_STUDENT_REQUEST = 'FETCH_GRADES_BY_STUDENT_REQUEST';
export const FETCH_GRADES_BY_STUDENT_SUCCESS = 'FETCH_GRADES_BY_STUDENT_SUCCESS';
export const FETCH_GRADES_BY_STUDENT_FAILURE = 'FETCH_GRADES_BY_STUDENT_FAILURE';

export const FETCH_GRADES_BY_COURSE_REQUEST = 'FETCH_GRADES_BY_COURSE_REQUEST';
export const FETCH_GRADES_BY_COURSE_SUCCESS = 'FETCH_GRADES_BY_COURSE_SUCCESS';
export const FETCH_GRADES_BY_COURSE_FAILURE = 'FETCH_GRADES_BY_COURSE_FAILURE';

export const FETCH_STUDENTS_WITH_COURSES_REQUEST = 'FETCH_STUDENTS_WITH_COURSES_REQUEST';
export const FETCH_STUDENTS_WITH_COURSES_SUCCESS = 'FETCH_STUDENTS_WITH_COURSES_SUCCESS';
export const FETCH_STUDENTS_WITH_COURSES_FAILURE = 'FETCH_STUDENTS_WITH_COURSES_FAILURE';

